@startuml
abstract class "Osoba" as Osoba {
    ID: String
    heslo: String
}
note top of Osoba
    Dědičnost typu {incomplete, disjoint}
end note

class "Zaměstnanec" as Zamestnanec {
}

Osoba <|-- Zamestnanec

note top of Zamestnanec
    Dědičnost typu {incomplete, overlapping}
end note

class "SprávceÚkolů" as SpravceUkolu {
}
Zamestnanec <|-- SpravceUkolu
SpravceUkolu "1" --> "0..n" DefiniceUkolu : definoval

abstract class "Plnitel" as Plnitel {
}
Osoba <|-- Plnitel
note top of Plnitel
    Dědičnost typu {complete, disjoint}
end note

class "Klient" as Klient {
}
Plnitel <|-- Klient

class "Pacient" as Pacient {
}
Plnitel <|-- Pacient

abstract class "DefiniceÚkolu" as DefiniceUkolu {
    ID: String
}

class "DefiniceFormuláře" as DefiniceFormuláře {
    data
}
DefiniceUkolu <|-- DefiniceFormuláře

class "ZadáníÚkolu" as ZadáníÚkolu {
    ID: String
    splnitDo: Date
    zadáno: Date
    opakování: TimeSpan
}
ZadáníÚkolu "1" --> "1" DefiniceUkolu : definováno
ZadáníÚkolu "1" --> "1" Plnitel : zadán pro
ZadáníÚkolu "1" --> "0..1" VypracováníÚkolu : vypracování

abstract class "VypracováníÚkolu" as VypracováníÚkolu {
    ID: String
    datumVypracování: Date
}

class "VypracováníFormuláře" as VypracováníFormuláře {
    data
}
VypracováníFormuláře --|> VypracováníÚkolu

class "ZadavatelÚkolů" as ZadavatelUkolu {
}
Zamestnanec <|-- ZadavatelUkolu
ZadavatelUkolu "1" --> "0..n" ZadáníÚkolu : zadal

class "AnalýzaVypracováníFormuláře" as AnalýzaVypracováníFormuláře {
    data
}
AnalýzaVypracováníFormuláře "1" --> "1" VypracováníFormuláře : analyzuje

class "NedokončenéVyplněníFormuláře" as NedokončenéVyplněníFormuláře {
    data
}
NedokončenéVyplněníFormuláře "0..n" --> "1" DefiniceFormuláře : vyplňuje
Plnitel "1" --> "0..n" NedokončenéVyplněníFormuláře : vlastní
NedokončenéVyplněníFormuláře "0..1" --> "1" ZadáníÚkolu : částečně vypracovává

@enduml