@startuml
abstract class "Osoba" as Osoba {
    ID: String
    heslo: String
}
note top of Osoba
    Dědičnost typu {incomplete, disjoint}
end note

class "Zaměstnanec" as Zamestnanec {
}

Osoba <|-- Zamestnanec

note top of Zamestnanec
    Dědičnost typu {incomplete, overlapping}
end note

class "SprávceÚkolů" as SpravceUkolu {
}
Zamestnanec <|-- SpravceUkolu
SpravceUkolu "1" --> "0..n" DefiniceUkolu : definoval

abstract class "Plnitel" as Plnitel {
}
Osoba <|-- Plnitel
note top of Plnitel
    Dědičnost typu {complete, disjoint}
end note

class "Klient" as Klient {
}
Plnitel <|-- Klient

class "Pacient" as Pacient {
}
Plnitel <|-- Pacient

abstract class "DefiniceÚkolu" as DefiniceUkolu {
    ID: String
}

class "DefiniceFormuláře" as DefiniceFormulare {
    data
}
DefiniceUkolu <|-- DefiniceFormulare

class "ZadáníÚkolu" as ZadaniUkolu {
    ID: String
    splnitDo: Date
    zadáno: Date
    opakování: TimeSpan
}
ZadaniUkolu "1" --> "1" DefiniceUkolu : definováno
ZadaniUkolu "1" --> "1" Plnitel : zadán pro
ZadaniUkolu "1" --> "0..1" VypracovaniUkolu : vypracování

abstract class "VypracováníÚkolu" as VypracovaniUkolu {
    ID: String
    datumVypracování: Date
}

class "VypracováníFormuláře" as VypracováníFormuláře {
    data
}
VypracováníFormuláře --|> VypracovaniUkolu

class "ZadavatelÚkolů" as ZadavatelUkolu {
}
Zamestnanec <|-- ZadavatelUkolu
ZadavatelUkolu "1" --> "0..n" ZadaniUkolu : zadal

class "AnalýzaVypracováníFormuláře" as AnalýzaVypracováníFormuláře {
    data
}
AnalýzaVypracováníFormuláře "1" --> "1" VypracováníFormuláře : analyzuje

class "NedokončenéVyplněníFormuláře" as NedokonceneVyplneniFormulare {
    data
}
NedokonceneVyplneniFormulare "0..n" --> "1" DefiniceFormulare : vyplňuje
Plnitel "1" --> "0..n" NedokonceneVyplneniFormulare : vlastní
NedokonceneVyplneniFormulare "0..1" --> "1" ZadaniUkolu : částečně vypracovává

@enduml