@startuml
skinparam dpi 300
skinparam defaultFontSize 30
skinparam defaultTextAlignment center

|Uživatel|
|Správa formuláře|
|Správa nedokončených vyplnění|

|Uživatel|
start

:Částečně vyplní\nformulář;
|Správa formuláře|
:Uloží částečně\nvyplněný formulář;
|Uživatel|
:Dokončí vyplnění\nformuláře;
:Odešle vyplněný\nformulář;
|Správa formuláře|
:Uloží vyplněný formulář;
fork
    :Informuje o\núspěšném uložení;
    |Uživatel|
    :Obdrží informaci\no úspěšném uložení;
    end
fork again
    |Správa formuláře|
    :Informuje o\núspěšném uložení;
    |Správa nedokončených vyplnění|
    :Smaže částečne vyplněný\nformulář pro daný formulář\nvlastněný uživatelem;
    end

@enduml