name: Validate PDF/A

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    name: Build thesis PDFs
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }
    defaults:
      run:
        working-directory: src

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y inkscape

      - uses: actions/checkout@v3
      - name: Build the thesis
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: src/*.pdf

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: 'ghcr.io/mff-cuni-cz/cuni-thesis-validator' }

    steps:
      - name: Get PDFs
        uses: actions/download-artifact@v3
      - name: Run VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0"'
