name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDFs and upload
    runs-on: ubuntu-latest
    container: { image: "aergus/latex" }
    defaults:
      run:
        working-directory: src

    env:
      # Secrets are configured on github.com in repository settings
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: lib
        run: apt-get update && apt-get install -y inkscape graphviz

      - name: Build the thesis
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: src/*.pdf

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Prepare folder with static assets
        run: >-
          mkdir -p ../website/public &&
          cp prace.pdf abstrakt.pdf abstrakt-en.pdf ../website/public

      - name: Pull Vercel Environment Information
        working-directory: ../website/
        run: vercel pull --yes --environment=production --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ../website/
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ../website/
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: "ghcr.io/mff-cuni-cz/cuni-thesis-validator" }

    steps:
      - name: Get PDFs
        uses: actions/download-artifact@v3
      - name: Run VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0"'